/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mochammad Alauddin
 */
public class Program_aritmatika extends javax.swing.JFrame {
    String jns = "";
    int jml;
    /**
     * Creates new form Program_aritmatika
     */
    public Program_aritmatika() {
        initComponents();
        jns = null;
            jPanel1.setVisible(false);
            bil1.setVisible(false);
            bil2.setVisible(false);
            bil3.setVisible(false);
            bil4.setVisible(false);
            b1.setVisible(false);
            b2.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JPane = new javax.swing.JTextPane();
        jmlBil = new javax.swing.JComboBox<>();
        ket = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Program Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(84, 11, 235, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 40, 160, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu--", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(230, 50, 160, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setText("Jumlah Bilangan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(36, 56, 120, 14);

        b1.setText("Bilangan 1");
        jPanel1.add(b1);
        b1.setBounds(36, 90, 80, 14);

        b2.setText("Bilangan 2");
        jPanel1.add(b2);
        b2.setBounds(36, 131, 100, 14);

        b3.setText("Bilangan 3");
        jPanel1.add(b3);
        b3.setBounds(36, 172, 100, 14);

        b4.setText("Bilangan 4");
        jPanel1.add(b4);
        b4.setBounds(36, 213, 100, 14);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        jPanel1.add(bil1);
        bil1.setBounds(166, 82, 183, 30);

        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        jPanel1.add(bil2);
        bil2.setBounds(166, 123, 183, 30);

        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        jPanel1.add(bil3);
        bil3.setBounds(166, 164, 183, 30);

        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });
        jPanel1.add(bil4);
        bil4.setBounds(166, 205, 183, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(166, 246, 86, 37);

        jScrollPane3.setViewportView(JPane);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(45, 289, 291, 83);

        jmlBil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jmlBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlBilActionPerformed(evt);
            }
        });
        jPanel1.add(jmlBil);
        jmlBil.setBounds(166, 51, 40, 25);

        ket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ket);
        ket.setBounds(134, 19, 112, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 390, 390);

        setBounds(0, 0, 430, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            jPanel1.setVisible(true);
            jmlBil.setEnabled(true);
        }
        else if (jComboBox1.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan ");
            jPanel1.setVisible(true);
            jmlBil.setEnabled(true); 
        }
        else if (jComboBox1.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            jPanel1.setVisible(true);
            jmlBil.setEnabled(true); 
        }
        else if (jComboBox1.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            jPanel1.setVisible(true);
            jmlBil.setEnabled(true); 
        }else {
            jns = null;
            jPanel1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void getJumlah(){
        if(jmlBil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 2;
        }else if (jmlBil.getSelectedItem().equals("3")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }else if (jmlBil.getSelectedItem().equals("4")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    }
    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil4ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil3ActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void jmlBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlBilActionPerformed
        getJumlah();
    }//GEN-LAST:event_jmlBilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1, a2 , a3 , a4 ;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
        if (jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                JPane.setText(""+a1+" + "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                JPane.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                JPane.setText(""+a1+" + "+a2+ " + "+a3+" + "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                JPane.setText(""+a1+" - "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                JPane.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 + a3 - a4;
                JPane.setText(""+a1+" - "+a2+ " - "+a3+" - "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                JPane.setText(""+a1+" x "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                JPane.setText(""+a1+" x "+a2+" x "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                JPane.setText(""+a1+" x "+a2+ " x "+a3+" x "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                JPane.setText(""+a1+" : "+a2+" = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                JPane.setText(""+a1+" : "+a2+" : "+a3+" = "+hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                JPane.setText(""+a1+" : "+a2+ " : "+a3+" : "+a4+" = "+hsl);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane JPane;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> jmlBil;
    private javax.swing.JLabel ket;
    // End of variables declaration//GEN-END:variables
}
